### ISSUE TITLE
Validate Required Variables

### ISSUE THREAD

**Issue by dylan-smith** [jessehouwing/azure-pipelines-variable-tasks#2]
Would be nice to indicate that a variable is required (at queue time), and have that validated when this task runs.

Today I do this by adding a custom powershell task, passing the various required variables as arguments, then checking that they all have values in the powershell.  This is a pain in the but to do everytime.

**Comment by jessehouwing** [comment]
Would this simply be a list of variables and if the value is $null or "", write an error?

**Comment by dylan-smith** [comment]
Sure that would work.  I just want somebody to make it easy for me to fail the build if certain variables aren't filled in.  And not have to author a custom powershell script to do it.

If you're task allowed me to specify a list of variables, that would do it.
Or if I decorate my required variables somehow.  e.g. Foo = $(Required) and your task looks for that to validate them.

Ultimately I don't really care how it's implemented, so long as it makes it easy and convenient to achieve my goal of failing the build if somebody doesn't fill in a value at queue time.

**Comment by jessehouwing** [comment]
So far I haven't figured out how to get all build variables from a build
task, I need to request them by name.

There is a IVariableService I may be able to access, but I haven't figured
it out yet.

I'd want the ability to expand * as well, or allow wildcards in variable
names.

**Comment by naeemsarfraz** [comment]
@jessehouwing [This is a script](https://gist.github.com/naeemsarfraz/a20ff14aea72a479ab664e304b31e02e) I use to help check runtime values for variables available in a powershell script during a build.

You'll recognise most of the standard TFS Build variables but the following line is the most interesting as it gets all vars currently in memory:

`Get-Variable |%{ Write-Host ("Name : {0}, Value: {1}" -f $_.Name,$_.Value ) }`

**Comment by jessehouwing** [comment]
I can easily access the available tasks through the VSTS task sdk. I just haven't gotten around to building this feature. I'm also still not sure how you'd want this feature implemented.

**Comment by ipip2005** [comment]
Also, variable validation should happen before getting the sources which takes around 5 minutes for our repo. Most time it's meaningless to run any tasks if the variable is not usable.
