### ISSUE TITLE
Replace transform - all occurances

### ISSUE THREAD

**Issue by bo-stig-christensen** [jessehouwing/azure-pipelines-variable-tasks#25]
When transforming variables using 'Basic' mode the transformation only takes place on the first entry in the input value.

For example, I would like to take my build number and replace '.' with '_'.
Input: '1.0.0.0'
Expected Output: '1_0_0_0'
Actual Output: '1_0.0.0'

The tranformation should have an option to replace all occurences of the search pattern and not only the first.

A workaround for now is using 'Rregex Replace' mode with the 'g' modifier.

**Comment by jessehouwing** [comment]
As a workaround, use Regex Replace and specify `\.` to be replaced with `_`. Javascript doesn't have a ReplaceAll function on strings and the alternatives are all depending on using Regex instead anyway.

**Comment by jessehouwing** [comment]
I'm open for a pr, this would be easy to add.

**Comment by jessehouwing** [comment]
It seems replace all is a wasps nest. Using Regex is a much easier option. I've gone over a number of packages, but every implementation seems to have issues.

Basic while loop can end up diving into an infinite loop. Don't want to DDosyour builds

**Comment by brumargues** [comment]
I've open an PR with a fix suggestion - https://github.com/jessehouwing/vsts-variable-tasks/pull/38
