### ISSUE TITLE
Increment variable

### ISSUE THREAD

**Issue by ciaagent** [jessehouwing/azure-pipelines-variable-tasks#37]
I am trying to increment a $(RetryCount) variable which is originally set = 0 using Transform Variable.
I tried the settings shown below, but now the new variable is '0 + 1'

Is what I am trying to do possible? If so what am I doing wrong.

Thank you!

![image](https://user-images.githubusercontent.com/11871798/47802908-4f4cbb00-dcff-11e8-8f7b-3c948f780fe5.png)

**Comment by IanYates** [comment]
It's a string-based setter, so unfortunately you're getting exactly as designed.

Nice idea for an additional type of transform though...

**Comment by jaylevin** [comment]
Any plan to introduce this?

**Comment by jessehouwing** [comment]
you can use counter expressions for this. No plans to support this in this task.
