### ISSUE TITLE
Set variable to variable group

### ISSUE THREAD

**Issue by tutike2000** [jessehouwing/azure-pipelines-variable-tasks#41]
Would it be possible to 'permanently' set a variable in a variable group, so that other builds/releases can use it?

This is currently a bit difficult (requiring a PUT/POST to https://YourVSTSName.visualstudio.com/YourProjName/apis/distributedtask/variablegroups , and requires your agent to grant access to its OAuth token)

**Comment by jessehouwing** [comment]
No, currently not supported. Would love a pull request. Tasks always have access to the OAuth token, so that shouldn't be the problem.
