### ISSUE TITLE
Update to latest task-lib contains a breaking change

### ISSUE THREAD

**Issue by dannyfhalpotia** [jessehouwing/azure-pipelines-variable-tasks#48]
Hi, 

The update from azure-pipelines-task-lib v2.8.0 to v2.9.3 contains a breaking change since special characters like % are now being encoded. This means that when using the set-variable task and the variable value contains a % sign it will now be encoded whereas it wasn't before the update. 

I consider this a breaking change so the task version for set-variable should really be bumped a major version so we can at least control when we want to upgrade in Azure DevOps and not have our build break overnight. 

Offending Commit: https://github.com/jessehouwing/azure-pipelines-variable-tasks/commit/c5e66ba2a6df8e09a16fcc8594e500584964cbef

Ongoing discussion in azure-pipeline-task-lib repo: https://github.com/microsoft/azure-pipelines-task-lib/issues/627

**Comment by jessehouwing** [comment]
ARGH. Sorry to hear this.

The older version has a security vulnerability, hence the upgrade from my
side. I'll look into this tomorrow.

**Comment by jessehouwing** [comment]
Should be fixed (and configurable) in 1.3.8 which I just pushed.

**Comment by dannyfhalpotia** [comment]
Thanks for the quick fix!
