### ISSUE TITLE
Transform Value Not Outputting To Variable

### ISSUE THREAD

**Issue by jeremymwilton** [jessehouwing/azure-pipelines-variable-tasks#50]
Since the last checkin it appears that the Azure DevOps task "Transform value" is not actually creating the variable specified. It's instead going to testvar. I'm using version 1.3.8.

![image](https://user-images.githubusercontent.com/16469173/79284530-c7fdf380-7e6f-11ea-80c5-4aa75964f388.png)

**Comment by jeremymwilton** [comment]
Opps...

![image](https://user-images.githubusercontent.com/16469173/79284977-00ea9800-7e71-11ea-9e3d-0bc469cb6860.png)

**Comment by ErrCode** [comment]
As a drastic workaround to remove our dependency on this task (we suddenly found all our pipelines were broken and so lost trust in it), switched to a PowerShell task to set variables instead. 

How to do this is described [here](https://gregorsuttie.com/2019/05/01/azure-devops-pass-variables-between-tasks/), but basically:
1. Create a Pipeline Variable for the pipeline you're wishing to use the variable within (leave the value blank or put in a useful default value). The following assumes `Version` is the variable name
2. Add PowerShell task into the pipeline
3. In the PowerShell task's Script: 
`Write-Output "##vso[task.setvariable variable=Version]1.2.3"`

**Comment by jessehouwing** [comment]
My apologies. In an attempt to (too) quickly fix another issue that was introduced by the new tasklib version this snuck in. Teaches me to not do bugfixes at 1am.

New version rolling out now.

In the advanced section there war an option to use a different way to set the variable which should still have worked.

**Comment by jessehouwing** [comment]
1.3.9 just shipped.
