### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by israserg** [jessehouwing/azure-pipelines-variable-tasks#51]
Hi
The last version of "Set variable" task (1.3.8) has a serious breaking change or bug
Starting from today morning the task stopped to do its work
Instead of setting a needed variable the task sets some "testvar" variable that unusable
As result all our pipelines were broken
Our instance of TFS on prem 2018 has an automatic update of extensions, and looks like it cannot be disabled so we get an updates in force manner
Setting "Use tasklib" parameter fixes the problem but I think it should be turned on by default
Such changes to task should bump a major/minor version so it will be possible to control upgrading

Thank you

**Comment by jessehouwing** [comment]
Has already been fixed. My apologies.
