### ISSUE TITLE
Update broke my releases.

### ISSUE THREAD

**Issue by rvande3** [jessehouwing/azure-pipelines-variable-tasks#52]
I am an admin for a large company, and use your task in hundreds, if not thousands, of Azure DevOps Server release pipelines. Your update yesterday has broken all of my customers that use your tasks. the Set Variable is used to set a "DeployDropPath" that fails later in the pipeline to see $(DeployDropPath) as a variable. It sees it as a literal now. Ex.. Set DeployDropPath as "F:\build\agent1\r21\drop" then later in a copy files task it tries to copy to the literal path: "$(DeployDropPath)\**". You need to fix this or roll back your change.

**Comment by jessehouwing** [comment]
Has already been fixed. My apologies.

**Comment by rvande3** [comment]
I have not seen an update since yesterday on my instance. This is still an issue. Do you have the .visx to update it?

____________________________

Ross VanDerSchaegen | Optum
Principal IO Engineering, Azure DevOps Server Admin
Enterprise Enablement & Platform Services

12125 Technology Drive, Eden Prairie, MN 55344, USA
T      +1(952) 833-6184
ross_vanderschaegen@optum.com<mailto:ross_vanderschaegen@optum.com>
www.optum.com

[cid:image002.jpg@01D61320.A6511060]

**Comment by jessehouwing** [comment]
It's on the marketplace.

https://marketplace.visualstudio.com/acquisition?itemName=jessehouwing.jessehouwing-vsts-variable-tasks

**Comment by jessehouwing** [comment]
Not sure it TFS has a timed job to schedule to check for extensions. Restarting the TFS job agent may do the trick.

**Comment by jessehouwing** [comment]
In the mean time you could enable the 'use tasklib' option under the new advanced section as a workaround.

**Comment by rvande3** [comment]
First let me say thank you for your response. The task is awesome and has been working great for years. I know you don’t hear that enough. Secondly, I found that just reverting back to version 0 is a viable workaround and have posted a quick blog on our support site about how to change it for our customers. I will wait for the update to run later tonight and see what happens. I have 11000 developers that use our system and bringing it down is not an option. ☺

Thanks again for the quick response.

____________________________

Ross VanDerSchaegen | Optum
Principal IO Engineering, Azure DevOps Server Admin
Enterprise Enablement & Platform Services

12125 Technology Drive, Eden Prairie, MN 55344, USA
T      +1(952) 833-6184
ross_vanderschaegen@optum.com<mailto:ross_vanderschaegen@optum.com>
www.optum.com

[cid:image002.jpg@01D61323.9EACDBC0]
