### ISSUE TITLE
Settin IsOutput=true not is not working when using TaskLib=true (default) option.

### ISSUE THREAD

**Issue by megedsh** [jessehouwing/azure-pipelines-variable-tasks#522]
Parameter is not passed on : 

https://github.com/jessehouwing/azure-pipelines-variable-tasks/blob/13deb24d5c6b89fb120699f11e00e616d568b77a/vsts-variable-set/v3/vsts-variable-set.ts#L51

when setting useTasklib=false the task is not setting the variable at all

**Comment by jessehouwing** [comment]
Fix rolling out now.
