### ISSUE TITLE
Suggestion: Version management of extension

### ISSUE THREAD

**Issue by mlooise** [jessehouwing/azure-pipelines-variable-tasks#54]
Hello,

First of all thank you for all your work on this extension. We are quite enthusiastic users of this task. We have however had a bit of a bad experience yesterday with the broken version that caused some deployments to production to fail. It turned out that it had been fixed in the meantime so luckely after some time it started working again. But this made me think about how this versioning works in TFS. Normally a pipeline 'freezes' or instantiates its pipeline on creation and once created the version of the extensions remain the same. What I saw here however was different. We did an earlier deployment to a Test environment which went fine. However on the production stage we encountered an error. So my guess is that in the meantime (between Test and Production) the version got updated. 

![image](https://user-images.githubusercontent.com/2109791/79451192-6b711480-7fe6-11ea-9d09-7291281d428d.png)

Which was true as you can see above.

I hoped this would never happen and as a result a deployment to Test would use the exact same extensions (and version) as Production. However this seems not te be the case. 

I think this might be down to that the extension is always listed as version 1.0 (or is this only the case for us?) And TFS updates the extensions but because this is always 1.0 it seems to replaces the existing instance. 

he extension very nicely has a semver but I think it would help if this version was also used in the task itself. Then a new version would not automatically be used in a pipeline already made. So then the user decides to upgrade or not. Now TFS (or the clock or the builder of the extension) decides. 

![image](https://user-images.githubusercontent.com/2109791/79450782-ac1c5e00-7fe5-11ea-9a73-4fab6fad8089.png)

Is this something your recognise and would consider changing?

Hope to hear from you and thanks again :)

**Comment by jessehouwing** [comment]
I make too many small updates which would flood the drop-down with a gazillion versions to choose from. Plus maintaining versions of tasks side-by-side is a huge pain. Plus it will prevent me from pushing security updates.

If you want control, you can work the repo, create a private version of the extension and have total control over when versions are shipped.

If you check the sources you can see there are multiple folders, one with v0 and one with v1 and e can maintain, secure and update the minor version of these tasks individually. That's how things work.

What I should really do is:
 * Create a test harness to prevent mistakes like this one.
 * Not hit publish 5 minutes before going to bed in the middle of the night.

For TFS you could change the schedule for the job that does the marketplace sync, or turn it off completely and only run it manually.

Another option is to download the vsix from the marketplace, install it to the local extension gallery and manually check for updates.

**Comment by jessehouwing** [comment]
If you'd crack open the vsix of the extension, you'll see that each task has a unique version number. My guess is that you could delete the broken version from your TFS instance with `tfx build tasks /delete` as well.
