### ISSUE TITLE
Secrets are shown in output!!

### ISSUE THREAD

**Issue by ThomasDThomsen** [jessehouwing/azure-pipelines-variable-tasks#55]
In recent version 1.3.9, there is a security issue with the VariableTransformTask@1, as it's now printing out the secrets!!
![image](https://user-images.githubusercontent.com/57177265/79844982-b6ab6e80-83bc-11ea-9b59-bdf09cf8124a.png)
![image](https://user-images.githubusercontent.com/57177265/79845124-e2c6ef80-83bc-11ea-92bd-a81279f7945b.png)

The pipeline code:
![image](https://user-images.githubusercontent.com/57177265/79845253-10ac3400-83bd-11ea-9437-5fc3ec571999.png)

**Comment by haljin** [comment]
Could it be because
```
console.log(`##vso[task.setvariable variable=${variable};isSecret=;${ isSecret ? 'true' : 'false' }]${value}`);
```
Should be
```
console.log(`##vso[task.setvariable variable=${variable};isSecret=;${ isSecret ? 'true' : 'false' };]${value}`);
```

i.e. the semicolon is in the wrong spot?

**Comment by jessehouwing** [comment]
As a workaround, can you turn on the 'use task lib' in the advanced
section? I'll test and release a fix later today.

**Comment by jessehouwing** [comment]
Thanks for reporting. Fix is rolling out.
