### ISSUE TITLE
Azure DevOps Server 2020 - Latest version 2.0.47 causes validation error

### ISSUE THREAD

**Issue by FranzKohl** [jessehouwing/azure-pipelines-variable-tasks#66]
The update to the latest version 2.0.47 does not work, neither by automatic update directly through the Azure DevOps Server 2020 App-Tier nor by downloading the extension (.vsix file) and trying to update the former version (1.3.10) with the locally downloaded file.

Finally, I removed the old version 1.3.10 and uploaded 2.0.47 from the local file - the error that appears in the dialog after clicking on the "Error"-link nearby the extension in the gallery is identical to the one shown their after the automatic update:

> Extension validation error
> 
> Task definition visible rule 'variableName=release.releasename' is invalid. It should be of format "A \<validconditionhere\> B" for Task with ID '9ccfb3bb-7ec0-4626-8599-164b1f95f933'.

See also screenshot attached.

@jessehouwing - I hope this issue can be fixed soon, as our users heavily rely on this task.

![2022-01-07 13_13_56-Manage Extensions _ Available extensions - Azure DevOps Server and 5 more pages ](https://user-images.githubusercontent.com/44869700/148550118-3c24359c-19d7-42a8-865b-4df7fb9abfbf.jpg)

**Comment by jessehouwing** [comment]
I can't really. 

Microsoft needs to patch their marketplace since they accidentally added too strict validation rules to the marketplace. It was patched on the service already. Azure DevOps 2022 should surely get that fix and I'm hoping 2020.2 will too. I'll ping some folks inside if Azure DevOps to see whether they can take care of that.

I suspect your server will still have the V1 version available and that should work for most cases.

As a workaround you can manually publish the tasks, they are updated to rarely that it shouldn't cause any issues or major maintenance woes.

Unzip the vsix and manually push the tasks using

```
tfx build tasks install --path ./taskname/v2
```

As an alternative you can remove the visibleRule from the task.json files.

**Comment by jessehouwing** [comment]
What e can do, is to publish the taskzips separately on the GitHub release page to make this process easier.

**Comment by FranzKohl** [comment]
> I can't really.
> 
> Microsoft needs to patch their marketplace since they accidentally added too strict validation rules to the marketplace. It was patched on the service already. Azure DevOps 2022 should surely get that fix and I'm hoping 2020.2 will too. I'll ping some folks inside if Azure DevOps to see whether they can take care of that.
> 
> I suspect your server will still have the V1 version available and that should work for most cases.
> 
> As a workaround you can manually publish the tasks, they are updated to rarely that it shouldn't cause any issues or major maintenance woes.
> 
> Unzip the vsix and manually push the tasks using
> 
> ```
> tfx build tasks install --path ./taskname/v2
> ```
> 
> As an alternative you can remove the visibleRule from the task.json files.

Understood. That means, it happens because ADS 2020.1 doesn't contain the necessary related fix on the "Marketplace client side", right?

That also means, once I'd reinstall your V1 version, it would restart checking for updates (ADS is doing that on a daily basis, I cannot switch this of on a per-extension-basis), causing me daily entries in the ADS Job monitoring log...

Your suggestion to "...remove the visibleRule from the task.json files." would mean, I'd have to do that on each build server (in the tasks cache), if I don't want to update the task in the app-tier.

So, finally that means, I have only two choices right now:
a) Wait for 2020.2 (and hope, that the validation rules have been fixed), or
b) Upload a modified version of your V2 task to the app-tier (using tfx)

Correct?

**Comment by FranzKohl** [comment]
> What e can do, is to publish the taskzips separately on the GitHub release page to make this process easier.

Thanks for you fast responses and this offer!

If you talk about a taskzip where the problematic validation rules have been removed - great, would be highly appreciated.

Did / do the Azure DevOps folks tell you if the validation rules fix will be included in 2020.2? And is there a (tentative) release date available for 2020.2?

**Comment by jessehouwing** [comment]
The taskzips don't need to be modified. It's only the marketplace that's
broken, the tasks themselves work just fine.

Only if you want to publish the vsix, would you need to patch the
task.jsons. don't ask... I've had quite a fight over this issue.

**Comment by jessehouwing** [comment]
With regards to timeline for 2020.2 or 2020.1.2 or 2022, nothing yet.

**Comment by jessehouwing** [comment]
Now auto-generating the task-zips:
https://github.com/jessehouwing/azure-pipelines-variable-tasks/releases/tag/v2.0.51
